@echo off
echo Instalando dependências Python...
pip install -r requirements.txt
echo Executando as migrações do Django...
python manage.py migrate
echo Coletando arquivos estáticos...
python manage.py collectstatic --noinput

