# Define as configurações de construção e implantação globalmente
[build]
  # Comando de construção do seu projeto
  command = "npm run build"
  
  # Diretório onde os arquivos de construção são gerados
  publish = "dist/"

# Define redirecionamentos de URL
[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301
